package com.vitalink.app.util

/** Patient-language education derived from the supplied PCNA 2022 guide, pages 6, 9, 10 and 14.
 * Used only for educational questions; reported emergencies remain in the clinical response path.
 */
object PcnaPatientAdvice {
    fun answer(question: String, language: String): String? {
        val q = question.lowercase()
        fun has(vararg words: String) = words.any { it in q }
        val educational = has("what", "why", "how", "explain", "tell me", "can i", "should i", "advice", "suggest", "apa", "kenapa", "bagaimana", "boleh", "nasihat", "什么", "为什么", "如何", "怎么", "建议", "என்ன", "ஏன்", "எப்படி", "ஆலோசனை")
        if (!educational || has("my reading", "my latest", "my result", "bacaan saya", "我的读数", "என் அளவு")) return null
        var page = 9
        val texts = when {
            has("ejection", "hfref", "hfpef", "what is heart failure", "apa itu kegagalan", "什么是心", "射血", "இதய செயலிழப்பு என்றால்") -> { page = 6; listOf(
                "Heart failure means the heart cannot fill or pump effectively enough to meet the body's needs. It does not mean the heart has stopped. Ejection fraction describes the proportion of blood pumped out of the left ventricle with each beat. Heart failure can occur with a reduced or preserved ejection fraction. Ask your care team which type you have and how your treatment helps it.",
                "Kegagalan jantung bermaksud jantung tidak dapat mengisi atau mengepam darah dengan cukup berkesan untuk keperluan badan. Ia bukan bermaksud jantung berhenti. Fraksi ejeksi ialah bahagian darah yang dipam keluar daripada ventrikel kiri setiap denyutan. Kegagalan jantung boleh berlaku dengan fraksi ejeksi rendah atau terpelihara. Tanya pasukan rawatan jenis anda dan bagaimana rawatan membantu.",
                "心力衰竭是指心脏不能有效地充盈或泵血来满足身体需要，并不是心脏停止跳动。射血分数表示左心室每次收缩时泵出血液所占的比例。射血分数降低或保留时都可能发生心衰。请向医疗团队了解您的心衰类型，以及治疗如何帮助您。",
                "இதய செயலிழப்பு என்பது உடலின் தேவைக்கு ஏற்ப இதயம் இரத்தத்தை நிரப்பவோ வெளியேற்றவோ முடியாத நிலை; இதயம் நின்றுவிட்டது என்று பொருள் அல்ல. வெளியேற்ற விகிதம் என்பது ஒவ்வொரு துடிப்பிலும் இடது கீழறையிலிருந்து வெளியேறும் இரத்தத்தின் பங்கு. இந்த விகிதம் குறைந்திருந்தாலும் இயல்பாக இருந்தாலும் இதய செயலிழப்பு ஏற்படலாம். உங்கள் வகை மற்றும் சிகிச்சையின் பயனை மருத்துவக் குழுவிடம் கேளுங்கள்.") }
            has("exercise", "walk", "activity", "rehab", "senaman", "berjalan", "运动", "步行", "உடற்பயிற்சி", "நடை") -> listOf(
                "Regular activity can improve stamina and quality of life when heart failure is stable. Ask your team about cardiac rehabilitation and the activity level suitable for you. Start with short, comfortable walks, build up gradually and include rest breaks. Stop if you develop chest pain, dizziness or unusual breathlessness; severe or persistent symptoms need urgent medical help.",
                "Aktiviti tetap boleh meningkatkan stamina dan kualiti hidup apabila kegagalan jantung stabil. Tanya pasukan rawatan tentang pemulihan jantung dan tahap aktiviti yang sesuai. Mulakan dengan berjalan singkat yang selesa, tambah secara beransur dan berehat. Berhenti jika sakit dada, pening atau sesak nafas luar biasa; simptom teruk atau berterusan memerlukan bantuan segera.",
                "心衰稳定时，规律活动有助于改善耐力和生活质量。请咨询医疗团队是否适合心脏康复，以及适合您的活动量。先从短时间、舒适的步行开始，逐步增加并安排休息。如果出现胸痛、头晕或异常气促，请停止活动；症状严重或持续时应立即就医。",
                "இதய செயலிழப்பு நிலையாக இருக்கும்போது ஒழுங்கான உடல் இயக்கம் சகிப்புத்தன்மையையும் வாழ்க்கைத் தரத்தையும் மேம்படுத்தலாம். இதய மறுவாழ்வு மற்றும் உங்களுக்கு ஏற்ற இயக்கம் பற்றி மருத்துவக் குழுவிடம் கேளுங்கள். குறுகிய, சிரமமில்லாத நடையிலிருந்து தொடங்கி படிப்படியாக அதிகரித்து இடையில் ஓய்வெடுங்கள். நெஞ்சுவலி, தலைச்சுற்றல் அல்லது வழக்கத்திற்கு மாறான மூச்சுத்திணறல் வந்தால் நிறுத்துங்கள்; கடுமையான அல்லது நீடிக்கும் அறிகுறிக்கு உடனடி உதவி பெறுங்கள்.")
            has("salt", "sodium", "diet", "food", "garam", "makan", "盐", "饮食", "உப்பு", "உணவு") -> listOf(
                "Excess sodium can worsen fluid congestion in heart failure. Choose fresh foods more often, compare sodium per serving on labels and use herbs or spices instead of extra salt. Reduce salty sauces, instant noodles and processed meats. Follow your team's sodium target. Ask before using potassium-based salt substitutes, especially with kidney problems or heart-failure medicines.",
                "Natrium berlebihan boleh memburukkan pengumpulan cecair dalam kegagalan jantung. Pilih makanan segar, bandingkan natrium setiap hidangan pada label dan gunakan herba atau rempah menggantikan garam tambahan. Kurangkan sos masin, mi segera dan daging diproses. Ikut sasaran natrium pasukan rawatan. Tanya dahulu sebelum menggunakan pengganti garam berasaskan kalium, terutama jika ada masalah buah pinggang atau mengambil ubat jantung.",
                "过多的钠可能加重心衰的液体潴留。多选择新鲜食物，比较标签上每份食物的钠含量，用香草或香料代替额外加盐。减少咸酱料、方便面和加工肉类。遵循医疗团队给您的钠摄入目标；有肾脏问题或服用心衰药物时，使用含钾代盐前先咨询医生或药剂师。",
                "அதிக சோடியம் இதய செயலிழப்பில் திரவத் தேக்கத்தை மோசமாக்கலாம். புதிய உணவுகளைத் தேர்ந்தெடுத்து, பொட்டலத்தில் ஒரு பரிமாறலுக்கான சோடியத்தை ஒப்பிட்டு, கூடுதல் உப்புக்கு பதில் மூலிகைகள் அல்லது மசாலா பயன்படுத்துங்கள். உப்பான சாஸ், உடனடி நூடுல்ஸ் மற்றும் பதப்படுத்திய இறைச்சியைக் குறையுங்கள். மருத்துவக் குழு கூறிய அளவைப் பின்பற்றுங்கள். பொட்டாசியம் உள்ள உப்பு மாற்றுப் பொருளைப் பயன்படுத்துவதற்கு முன் ஆலோசனை பெறுங்கள்.")
            has("water", "fluid", "thirst", "minum", "cecair", "dahaga", "饮水", "液体", "口渴", "நீர்", "தாகம்") -> listOf(
                "A fluid limit is individual: use the limit prescribed by your care team, rather than a general internet target. Spread drinks through the day and use a measured cup or bottle. Include soups, ice and other liquids in the total. Small sips and mouth care may help thirst. If thirst, swelling or breathlessness is worsening, contact your team instead of changing your limit or medicine yourself.",
                "Had cecair adalah individu: gunakan had yang ditetapkan pasukan rawatan. Bahagikan minuman sepanjang hari dan gunakan cawan atau botol bersukat. Kira sup, ais dan cecair lain dalam jumlah keseluruhan. Tegukan kecil dan penjagaan mulut boleh membantu rasa dahaga. Jika dahaga, bengkak atau sesak nafas bertambah, hubungi pasukan rawatan dan jangan ubah had atau ubat sendiri.",
                "饮水限制因人而异，请按医疗团队给您的限制执行，不要套用网上的通用目标。把饮品分配到一天中，用有刻度的杯子或水瓶计量，并把汤、冰块等液体计入总量。小口饮水和口腔护理可能缓解口渴。如果口渴、肿胀或气促加重，请联系医疗团队，不要自行改变限水量或药物。",
                "திரவ வரம்பு ஒவ்வொருவருக்கும் வேறுபடும்; உங்கள் மருத்துவக் குழு கூறிய வரம்பைப் பயன்படுத்துங்கள். பானங்களை நாள் முழுவதும் பிரித்து, அளவுக் கோப்பை அல்லது பாட்டிலைப் பயன்படுத்துங்கள். சூப், பனிக்கட்டி மற்றும் பிற திரவங்களையும் மொத்தத்தில் சேருங்கள். சிறிய மிடறுகளும் வாய்ப் பராமரிப்பும் தாகத்துக்கு உதவலாம். தாகம், வீக்கம் அல்லது மூச்சுத்திணறல் அதிகரித்தால் வரம்பையோ மருந்தையோ தானாக மாற்றாமல் மருத்துவக் குழுவைத் தொடர்புகொள்ளுங்கள்.")
            has("medicine", "medication", "drug", "ubat", "药", "மருந்த") -> { page = 14; listOf(
                "Heart-failure medicines have different jobs: some reduce strain on the heart and improve long-term outcomes, while diuretics help remove excess fluid. Treatment depends on your heart-failure type, kidney function and other conditions. Keep an up-to-date medicine list and ask your pharmacist what each medicine does. If you miss a dose or notice side effects, ask for advice for that specific medicine; do not double doses or stop treatment on your own. Which medicine would you like explained?",
                "Ubat kegagalan jantung mempunyai fungsi berbeza: sesetengah mengurangkan beban jantung dan memperbaiki hasil jangka panjang, manakala diuretik membantu membuang cecair berlebihan. Rawatan bergantung pada jenis kegagalan jantung, fungsi buah pinggang dan keadaan lain. Simpan senarai ubat terkini. Jika tertinggal dos atau ada kesan sampingan, dapatkan nasihat khusus; jangan gandakan dos atau berhenti sendiri. Ubat mana yang ingin anda fahami?",
                "心衰药物有不同作用：一些减轻心脏负担并改善长期预后，利尿剂帮助排出多余液体。治疗取决于心衰类型、肾功能和其他疾病。请保留最新药物清单，并向药剂师了解每种药的作用。漏服或出现副作用时，应咨询该药的具体处理方法，不要自行加倍剂量或停药。您想了解哪一种药？",
                "இதய செயலிழப்பு மருந்துகளின் பணிகள் வேறுபடும்: சில இதயச் சுமையைக் குறைத்து நீண்டகால பலனை மேம்படுத்தும்; சிறுநீர் பெருக்கும் மருந்துகள் அதிக திரவத்தை வெளியேற்ற உதவும். சிகிச்சை இதய செயலிழப்பு வகை, சிறுநீரகச் செயல்பாடு மற்றும் பிற நிலைகளைச் சார்ந்தது. தற்போதைய மருந்துப் பட்டியலை வைத்திருங்கள். அளவு தவறினாலோ பக்கவிளைவு ஏற்பட்டாலோ குறிப்பிட்ட மருந்துக்கான ஆலோசனை பெறுங்கள்; தானாக இரட்டிப்பு அளவு எடுக்கவோ நிறுத்தவோ வேண்டாம். எந்த மருந்தைப் பற்றி விளக்கம் வேண்டும்?") }
            has("weight", "berat", "体重", "எடை") -> { page = 10; listOf(
                "A quick weight increase in heart failure can reflect extra fluid, rather than body fat. Compare readings taken under similar conditions: the same scale, at a similar time, after using the toilet and before breakfast. Watch for swelling, worsening breathlessness or needing more pillows. Report a rapid increase or worsening symptoms to your care team and follow their action plan; do not adjust diuretics yourself.",
                "Kenaikan berat mendadak boleh menunjukkan cecair berlebihan, bukan lemak. Bandingkan bacaan menggunakan penimbang dan masa yang sama, selepas ke tandas dan sebelum sarapan. Pantau bengkak, sesak nafas bertambah atau perlu lebih banyak bantal. Laporkan perubahan cepat kepada pasukan rawatan dan ikut pelan mereka; jangan ubah diuretik sendiri.",
                "心衰患者的体重快速增加可能表示体内积聚了液体，而不一定是脂肪。尽量用同一台秤，在相似时间、如上厕所后及早餐前测量并比较。留意肿胀、气促加重或睡觉需要更多枕头。体重快速增加或症状加重时请联系医疗团队，按照个人行动计划处理，不要自行调整利尿剂。",
                "திடீர் எடை அதிகரிப்பு கொழுப்பைவிட அதிக திரவத்தைக் குறிக்கலாம். அதே தராசில், ஒரே நேரத்தில், கழிப்பறைக்குப் பிறகு காலை உணவுக்கு முன் எடுத்த அளவுகளை ஒப்பிடுங்கள். வீக்கம், அதிக மூச்சுத்திணறல் அல்லது கூடுதல் தலையணை தேவைப்படுவதை கவனியுங்கள். வேகமான மாற்றத்தை மருத்துவக் குழுவிடம் தெரிவித்து அவர்களின் திட்டத்தைப் பின்பற்றுங்கள்; மருந்தைத் தானாக மாற்றாதீர்கள்.") }
            has("health", "heart failure", "advice", "suggest", "kesihatan", "nasihat", "jantung", "健康", "建议", "心衰", "ஆலோசனை", "உடல்நலம்") -> { page = 10; listOf(
                "For day-to-day heart-failure care, take medicines as prescribed, choose less salty foods and follow your personal fluid limit. If your condition is stable and your team agrees, build activity gradually with rest breaks. Notice changes in breathing, swelling and energy, and contact your team if they worsen. Which part would help you most today: food, activity, medicines or managing symptoms?",
                "Untuk penjagaan harian, ambil ubat mengikut arahan, pilih makanan kurang garam dan ikut had cecair peribadi. Jika keadaan stabil dan pasukan rawatan bersetuju, tambah aktiviti secara beransur dengan rehat. Perhatikan perubahan pernafasan, bengkak dan tenaga; hubungi pasukan rawatan jika bertambah teruk. Adakah anda ingin bantuan tentang makanan, aktiviti, ubat atau simptom?",
                "日常心衰管理可以从按处方服药、选择低盐食物，以及遵循个人饮水限制开始。病情稳定且医疗团队同意时，可逐步增加活动并安排休息。留意呼吸、肿胀和体力的变化，恶化时联系医疗团队。今天您最想了解饮食、活动、药物，还是症状处理？",
                "தினசரி பராமரிப்பில் மருந்தை பரிந்துரைத்தபடி எடுத்துக்கொண்டு, உப்பு குறைந்த உணவைத் தேர்ந்தெடுத்து, தனிப்பட்ட திரவ வரம்பைப் பின்பற்றுங்கள். நிலை சீராகவும் மருத்துவக் குழு ஒப்புதலுடனும் இருந்தால் ஓய்வு இடைவெளிகளுடன் இயக்கத்தை அதிகரிக்கலாம். மூச்சு, வீக்கம், சக்தியில் மாற்றம் மோசமானால் மருத்துவக் குழுவைத் தொடர்புகொள்ளுங்கள். உணவு, இயக்கம், மருந்து அல்லது அறிகுறிகளில் எதைப் பற்றி உதவி வேண்டும்?") }
            else -> return null
        }
        val index = when(language) { "ms", "rojak" -> 1; "zh" -> 2; "ta" -> 3; else -> 0 }
        return texts[index]
    }
}

